export const getCategoryList = ["To do", "Daily", "Weekly", "Monthly"];

export const getHomeErrands = [
  {
    categoryTitle: "To do",
    errands: [
      {
        id: 10,
        title: "Update operrands",
        notes: "check documentation for requirements",
        status: "To do",
        category: "To do",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "Daily",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [32],
      },
      {
        id: 11,
        title: "Check operrands analytics",
        notes: "check documentation for requirements",
        status: "To do",
        category: "To do",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "Monthly",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [1, 15],
      },
      {
        id: 12,
        title: "Check updates for tech stack used",
        notes: "Get data from firebase",
        status: "To do",
        category: "To do",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "Monthly",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [32],
      },
      {
        id: 12,
        title: "Add login feature",
        notes: "check documentation for requirements",
        status: "To do",
        category: "To do",
        dueDate: new Date("2024-11-16T16:00:00.000Z"),
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "None",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [32],
      },
      {
        id: 10,
        title: "Add search feature",
        notes: "check documentation for requirements",
        status: "To do",
        category: "To do",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "None",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [32],
      },
      {
        id: 11,
        title: "Check operrands analytics",
        notes: "check documentation for requirements",
        status: "To do",
        category: "To do",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "Monthly",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [1, 15],
      },
      {
        id: 12,
        title: "Add search feature",
        notes: "check documentation for requirements",
        status: "To do",
        category: "To do",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "None",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [32],
      },
      {
        id: 12,
        title: "Add search feature",
        notes: "check documentation for requirements",
        status: "To do",
        category: "To do",
        dueDate: new Date("2024-11-16T16:00:00.000Z"),
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "None",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [32],
      },
    ],
  },
  {
    categoryTitle: "Daily Errands",
    errands: [
      {
        id: 1,
        title: "Take vitamins",
        notes: "",
        status: "To do",
        category: "Daily",
        startDate: new Date("2024-11-07T12:21:01.358Z"),
        repeat: "Daily",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [1],
      },
      {
        id: 2,
        title: "Exercise for 30 mins",
        notes: "add jogging or cycling",
        status: "To do",
        category: "Daily",
        startDate: new Date("2024-11-11T16:00:00.000Z"),
        repeat: "Daily",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [1],
      },
      {
        id: 3,
        title: "Clean your desk",
        notes: "",
        status: "To do",
        category: "Daily",
        startDate: new Date("2024-11-11T16:00:00.000Z"),
        repeat: "Daily",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [1],
      },
    ],
  },
  {
    categoryTitle: "Weekly Errands",
    errands: [
      {
        id: 4,
        title: "Clean room",
        notes: "Lorem ipsum odor amet, consectetuer",
        status: "To do",
        category: "Weekly",
        startDate: new Date("2024-11-07T16:00:00.000Z"),
        repeat: "Weekly",
        repeatDayOfWeek: ["Sat"],
        repeatDayOfMonth: [1],
      },
      {
        id: 5,
        title: "Wash and fold clothes",
        notes: "Lorem ipsum odor amet, consectetuer",
        status: "To do",
        category: "Weekly",
        startDate: new Date("2024-11-07T13:06:50.665Z"),
        repeat: "Weekly",
        repeatDayOfWeek: ["Sun", "Sat"],
        repeatDayOfMonth: [1],
      },
      {
        id: 6,
        title: "Work updates",
        notes: "Lorem ipsum odor amet, consectetuer",
        status: "To do",
        category: "Weekly",
        startDate: new Date("2024-11-07T13:06:50.665Z"),
        repeat: "Weekly",
        repeatDayOfWeek: ["Mon", "Wed", "Fri"],
        repeatDayOfMonth: [1],
      },
      {
        id: 7,
        title: "Check reports",
        notes: "Lorem ipsum odor amet, consectetuer",
        status: "To do",
        category: "Weekly",
        startDate: new Date("2024-11-07T13:06:50.665Z"),
        repeat: "Weekly",
        repeatDayOfWeek: ["Tue", "Thu"],
        repeatDayOfMonth: [1],
      },
    ],
  },
  {
    categoryTitle: "Monthly Errands",
    errands: [
      {
        id: 8,
        title: "Pay rent",
        notes: "bank transfer to landlord",
        status: "To do",
        category: "Monthly",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "Monthly",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [32],
      },
      {
        id: 9,
        title: "Pay utility bills",
        notes: "water, electricity, internet",
        status: "To do",
        category: "Monthly",
        startDate: new Date("2024-11-07T13:47:31.079Z"),
        repeat: "Monthly",
        repeatDayOfWeek: ["Mon"],
        repeatDayOfMonth: [1, 15],
      },
    ],
  },
];
